name: Apply terraform

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  apply:
    name: Apply the gator terraform
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Check env var
        run: echo $TF_VAR_DO_DOMAIN
        
        # Replace the caddy server every time to force reconfigure
        # this is a stop gap until config is extracted from IaC
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -replace=digitalocean_droplet.caddy[*]
        env:
          TF_VAR_DO_DOMAIN: ${{ secrets.TF_VAR_DO_DOMAIN }}
          TF_VAR_DO_TOKEN: ${{ secrets.TF_VAR_DO_TOKEN }}
          TF_VAR_TAILSCALE_TOKEN: ${{ secrets.TF_VAR_TAILSCALE_TOKEN }}